# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(926, 625)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_OldText = QtWidgets.QLabel(self.centralWidget)
        self.label_OldText.setObjectName("label_OldText")
        self.verticalLayout.addWidget(self.label_OldText)
        self.label_RootFolder = QtWidgets.QLabel(self.centralWidget)
        self.label_RootFolder.setObjectName("label_RootFolder")
        self.verticalLayout.addWidget(self.label_RootFolder)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 2, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.comboBox_OldText = QtWidgets.QComboBox(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_OldText.sizePolicy().hasHeightForWidth())
        self.comboBox_OldText.setSizePolicy(sizePolicy)
        self.comboBox_OldText.setEditable(True)
        self.comboBox_OldText.setInsertPolicy(QtWidgets.QComboBox.InsertAtTop)
        self.comboBox_OldText.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.comboBox_OldText.setObjectName("comboBox_OldText")
        self.horizontalLayout.addWidget(self.comboBox_OldText)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label_NewText = QtWidgets.QLabel(self.centralWidget)
        self.label_NewText.setObjectName("label_NewText")
        self.horizontalLayout.addWidget(self.label_NewText)
        self.comboBox_NewText = QtWidgets.QComboBox(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_NewText.sizePolicy().hasHeightForWidth())
        self.comboBox_NewText.setSizePolicy(sizePolicy)
        self.comboBox_NewText.setEditable(True)
        self.comboBox_NewText.setInsertPolicy(QtWidgets.QComboBox.InsertAtTop)
        self.comboBox_NewText.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.comboBox_NewText.setObjectName("comboBox_NewText")
        self.horizontalLayout.addWidget(self.comboBox_NewText)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.toolButton_Text_Refresh = QtWidgets.QToolButton(self.centralWidget)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/arrow_refresh_32.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_Text_Refresh.setIcon(icon)
        self.toolButton_Text_Refresh.setObjectName("toolButton_Text_Refresh")
        self.horizontalLayout.addWidget(self.toolButton_Text_Refresh)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 1, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.comboBox_RootFolder = QtWidgets.QComboBox(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_RootFolder.sizePolicy().hasHeightForWidth())
        self.comboBox_RootFolder.setSizePolicy(sizePolicy)
        self.comboBox_RootFolder.setAcceptDrops(True)
        self.comboBox_RootFolder.setEditable(True)
        self.comboBox_RootFolder.setInsertPolicy(QtWidgets.QComboBox.InsertAtTop)
        self.comboBox_RootFolder.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.comboBox_RootFolder.setObjectName("comboBox_RootFolder")
        self.horizontalLayout_2.addWidget(self.comboBox_RootFolder)
        self.pushButton_RootFolder_Browse = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_RootFolder_Browse.setObjectName("pushButton_RootFolder_Browse")
        self.horizontalLayout_2.addWidget(self.pushButton_RootFolder_Browse)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.checkBox_Subfolders = QtWidgets.QCheckBox(self.centralWidget)
        self.checkBox_Subfolders.setObjectName("checkBox_Subfolders")
        self.horizontalLayout_2.addWidget(self.checkBox_Subfolders)
        self.checkBox_ExtractYear = QtWidgets.QCheckBox(self.centralWidget)
        self.checkBox_ExtractYear.setChecked(True)
        self.checkBox_ExtractYear.setObjectName("checkBox_ExtractYear")
        self.horizontalLayout_2.addWidget(self.checkBox_ExtractYear)
        spacerItem3 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.toolButton_RootFolder_Refresh = QtWidgets.QToolButton(self.centralWidget)
        self.toolButton_RootFolder_Refresh.setIcon(icon)
        self.toolButton_RootFolder_Refresh.setObjectName("toolButton_RootFolder_Refresh")
        self.horizontalLayout_2.addWidget(self.toolButton_RootFolder_Refresh)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.tableWidget_Files = QtWidgets.QTableWidget(self.centralWidget)
        self.tableWidget_Files.setAcceptDrops(True)
        self.tableWidget_Files.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_Files.setAlternatingRowColors(True)
        self.tableWidget_Files.setColumnCount(3)
        self.tableWidget_Files.setObjectName("tableWidget_Files")
        self.tableWidget_Files.setRowCount(0)
        self.tableWidget_Files.verticalHeader().setVisible(False)
        self.verticalLayout_2.addWidget(self.tableWidget_Files)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_MakeItSo = QtWidgets.QPushButton(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_MakeItSo.sizePolicy().hasHeightForWidth())
        self.pushButton_MakeItSo.setSizePolicy(sizePolicy)
        self.pushButton_MakeItSo.setObjectName("pushButton_MakeItSo")
        self.horizontalLayout_3.addWidget(self.pushButton_MakeItSo)
        self.pushButtoFiles_Clear = QtWidgets.QPushButton(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtoFiles_Clear.sizePolicy().hasHeightForWidth())
        self.pushButtoFiles_Clear.setSizePolicy(sizePolicy)
        self.pushButtoFiles_Clear.setObjectName("pushButtoFiles_Clear")
        self.horizontalLayout_3.addWidget(self.pushButtoFiles_Clear)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 926, 22))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menuBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setStyleSheet("background-color: rgb(211, 215, 207)")
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionAbout_Qt = QtWidgets.QAction(MainWindow)
        self.actionAbout_Qt.setObjectName("actionAbout_Qt")
        self.menuFile.addAction(self.actionQuit)
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addAction(self.actionAbout_Qt)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())
        self.label_OldText.setBuddy(self.comboBox_OldText)
        self.label_NewText.setBuddy(self.comboBox_NewText)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_OldText.setText(_translate("MainWindow", "Old Text"))
        self.label_RootFolder.setText(_translate("MainWindow", "Root Folder"))
        self.comboBox_OldText.setToolTip(_translate("MainWindow", "Text to be replaced in the file name."))
        self.label_NewText.setText(_translate("MainWindow", "New Text"))
        self.comboBox_NewText.setToolTip(_translate("MainWindow", "New text for the file name."))
        self.toolButton_Text_Refresh.setToolTip(_translate("MainWindow", "Refresh the list of files showing the new file names."))
        self.toolButton_Text_Refresh.setText(_translate("MainWindow", "..."))
        self.comboBox_RootFolder.setToolTip(_translate("MainWindow", "Folder containg the files to be renamed."))
        self.pushButton_RootFolder_Browse.setToolTip(_translate("MainWindow", "Browse for root folder"))
        self.pushButton_RootFolder_Browse.setText(_translate("MainWindow", "Browse"))
        self.checkBox_Subfolders.setToolTip(_translate("MainWindow", "Include subfolders."))
        self.checkBox_Subfolders.setText(_translate("MainWindow", "Subfolders"))
        self.checkBox_ExtractYear.setToolTip(_translate("MainWindow", "<html><head/><body><p>Set <span style=\" font-style:italic;\">New Text</span> to folder name year, if present.</p></body></html>"))
        self.checkBox_ExtractYear.setText(_translate("MainWindow", "Extract year"))
        self.toolButton_RootFolder_Refresh.setToolTip(_translate("MainWindow", "Refresh the root folder."))
        self.toolButton_RootFolder_Refresh.setText(_translate("MainWindow", "..."))
        self.pushButton_MakeItSo.setToolTip(_translate("MainWindow", "Rename the files."))
        self.pushButton_MakeItSo.setText(_translate("MainWindow", "Make It So"))
        self.pushButtoFiles_Clear.setToolTip(_translate("MainWindow", "Clear the list of file names."))
        self.pushButtoFiles_Clear.setText(_translate("MainWindow", "Clear"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionAbout_Qt.setText(_translate("MainWindow", "About Qt"))

